# .github/workflows/main.yml
name: Build, Test, Coverage & Sonar Analysis

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test, Coverage & Analyze
    runs-on: ubuntu-latest
    env:

      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:

      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   #

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # 3. Cache Sonar packages
      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 5. Build, run tests with JaCoCo and Sonar analysis
      - name: Run tests, generate coverage report & analyze with Sonar
        run: |
          mvn clean verify \
            org.jacoco:jacoco-maven-plugin:prepare-agent \
            org.jacoco:jacoco-maven-plugin:report \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=BasilOrg_Cooking_system \
            -Dsonar.organization=YourOrgName         #  SonarCloud
            -Dsonar.host.url=https://sonarcloud.io   # https://your-sonarqube-server
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
